### ISSUE TITLE
Simple demo

### ISSUE THREAD

**Issue by bhack** [aharley/pips2#1]
Other then `test_*` for the specific datasets do you have a minimal inference demo script for generic image sequences or video?

**Comment by aharley** [comment]
Hi, you're fast to find this. Yes, I'll be adding a minimal inference demo script today or tomorrow.

**Comment by MMathisLab** [comment]
(and a license please so it's usable 💜, if that is the intent)

**Comment by aharley** [comment]
done!

**Comment by bhack** [comment]
Thanks, It could be nice if you could expand it with query points like in co-tracker and tapir demos.
