### ISSUE TITLE
How much memory is required to evaluate the pod dataset?

### ISSUE THREAD

**Issue by eugenelyj** [aharley/pips2#4]
Congratulations on your great work!
I have a question, how much memory is required to evaluate pip++ on the pod dataset? There are 256 points on 128-length 512x896 videos.

**Comment by aharley** [comment]
The current setup asks for about 25G gpu memory. If you don't have this, I think you could lower N from 256 to 64 and get similar results, for about 20G.

**Comment by eugenelyj** [comment]
Thanks :)
