### ISSUE TITLE
Which one is the exact threshold to define tracking failure

### ISSUE THREAD

**Issue by eugenelyj** [aharley/pips2#6]
Hi, in the paper i see `Failure is when L2 distance exceeds 50 pixels in the normalized 256 × 256 resolution`. But in the code the sur_thres is assigned 16. So which one corresponds to the table in the paper?

**Comment by aharley** [comment]
Right, the paper used a threshold of 50. On thinking about how big 50 is within 256x256, I thought 16 might be more reasonable for the repo and future work. I think the right thing to do (as we did in the paper) is to re-run any baselines and re-measure things, to make sure everything is apples-to-apples.

**Comment by eugenelyj** [comment]
Make sense. Thank you :)
