### ISSUE TITLE
Visualize tracked points on long videos?

### ISSUE THREAD

**Issue by anruigu** [aharley/pips2#9]
It seems like the points get re-initialized every S frames in demo.py, so the resulting logs are chopped up into segments. 
And test_on_pod.py doesn't visualize the predictions.
I could probably manually chain the points in demo, but was wondering if there's a better way to visualize points for the entire video?

**Comment by aharley** [comment]
Thanks for the nice message. 

I've found it's not at all easy to show tracks more than ~50 frames long while keeping the visualization clear. (Even ground truth tracks start looking crazy.) Plus, tracking performance is usually bad beyond ~100 frames. So, I haven't spent much time trying to improve this yet. 

If you can help on this aspect, I would greatly appreciate it, and I can add it to the repo with an acknowledgement to you.

**Comment by anruigu** [comment]
Cool good to know, I ended up stitching together the trajectories for the whole video but haven't had the time to clean up that solution. Will do soon!
